package globals

// all possible command sequences
const (
	CMD_ENTER_NORMAL          = 0x00
	CMD_ENTER_INSPECT         = 0x01
	CMD_GET_ANALOG_SD_UPDATE  = 0xA0
	CMD_GET_ANALOG_LC_READING = 0xA1
	CMD_CLEAR_ANALOG_SD       = 0xAE
	CMD_GET_DIGITAL_SD_UPDATE = 0xB0
	CMD_GET_ALTIMETER_READING = 0xB1
	CMD_GET_SHOCK_1_READING   = 0xB3
	CMD_GET_IMU_READING       = 0xB5
	CMD_CLEAR_DIGITAL_SD      = 0xBE
	CMD_ENTER_LAUNCH_MODE     = 0x04
	CMD_TIMEOUT               = 0xFF
)
