package globals

// all possible command sequences
const (
	CMD_ENTER_NORMAL      = 0x00
	CMD_ENTER_INSPECT     = 0x01
	CMD_JUMP_CLK          = 0x0B
	CMD_TEST_SERIAL_CONN  = 0x0C
	CMD_ENTER_LAUNCH_MODE = 0x04

	CMD_GET_RADIO_SD_UPDATE = 0x20
	CMD_CLEAR_RADIO_SD      = 0x2E

	CMD_GET_ANALOG_V1_SD_UPDATE  = 0xA0
	CMD_GET_ANALOG_V1_PT_READING = 0xA2
	CMD_CLEAR_ANALOG_V1_SD       = 0xAE

	CMD_GET_DIGITAL_V1_SD_UPDATE         = 0xB0
	CMD_GET_DIGITAL_V1_ALTIMETER_READING = 0xB1
	CMD_GET_DIGITAL_V1_SHOCK_1_READING   = 0xB3
	CMD_GET_DIGITAL_V1_IMU_READING       = 0xB5
	CMD_CLEAR_DIGITAL_V1_SD              = 0xBE

	CMD_GET_ANALOG_V2_SD_UPDATE  = 0xC0
	CMD_GET_ANALOG_V2_PT_READING = 0xC2
	CMD_CLEAR_ANALOG_V2_SD       = 0xCE

	CMD_GET_DIGITAL_V2_SD_UPDATE         = 0xD0
	CMD_GET_DIGITAL_V2_GPS_READING       = 0xD1
	CMD_GET_DIGITAL_V2_ALTIMETER_READING = 0xD2
	CMD_GET_DIGITAL_V2_SHOCK_1_READING   = 0xD3
	CMD_GET_DIGITAL_V2_SHOCK_2_READING   = 0xD4
	CMD_GET_DIGITAL_V2_IMU_READING       = 0xD5
	CMD_CLEAR_DIGITAL_V2_SD              = 0xDE

	CMD_TIMEOUT = 0xFF
)
